// 初始树形数据...未复制完全
const originTreeData = {
  children: [
    {
      children: null,
      departmentId: "b213fddf-2ed4-4025-9f39-7c1fd73a7c8f",
      id: "a2186639-88bd-423b-bebe-6ee8e8a868a7",
      parentId: { present: true },
      resourceName: "保证金",
      resourcePermissions: ["UPDATE_MARGIN"],
      resourceType: "MARGIN",
    },
    {
      children: null,
      departmentId: "b213fddf-2ed4-4025-9f39-7c1fd73a7c8f",
      id: "60392a91-74f1-4b0e-9cd7-59d8927aeef7",
      parentId: { present: true },
      resourceName: "客户信息",
      resourcePermissions: [
        "UPDATE_CLIENT",
        "DELETE_CLIENT",
        "READ_CLIENT",
        "CREATE_CLIENT",
      ],
      resourceType: "CLIENT_INFO",
      sort: 0,
    },
    {
      children: [
        {
          id: "30899c52-3042-4ba5-bacd-0d7f76fd12f6",
          sort: 0,
          children: null,
          resourceName: "财务出入金",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "GRANT_ACTION",
            "BIND_PROCESS_TRIGGER",
          ],
        },
        {
          id: "1210a1b3-81d9-4d5a-a7e3-19b219db5867",
          sort: 0,
          children: null,
          resourceName: "触发器管理",
          resourceType: "TRIGGER",
          resourcePermissions: ["CREATE_TRIGGER", "GRANT_ACTION"],
        },
        {
          id: "c407933c-db0e-445f-afdf-17d4ee633adc",
          sort: 0,
          children: null,
          resourceName: "交易录入",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "GRANT_ACTION",
            "BIND_PROCESS_TRIGGER",
          ],
        },
        {
          id: "4d85201a-007e-44eb-8c28-820dabe648aa",
          sort: 0,
          children: null,
          resourceName: "交易要素修改",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "BIND_PROCESS_TRIGGER",
            "GRANT_ACTION",
          ],
        },
        {
          id: "92c22333-1de0-4d0c-8678-35ab1e700871",
          sort: 0,
          children: null,
          resourceName: "结算",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [],
        },
        {
          id: "41094c11-04b3-44b3-a960-4536711f90e0",
          sort: 0,
          children: null,
          resourceName: "开户",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "GRANT_ACTION",
            "BIND_PROCESS_TRIGGER",
          ],
        },
        {
          id: "f2bd770d-e8a5-4917-bd94-b5179f89d38f",
          sort: 0,
          children: null,
          resourceName: "授信额度变更",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "GRANT_ACTION",
            "BIND_PROCESS_TRIGGER",
          ],
        },
        {
          id: "8e08f500-dfe2-439e-ad14-ef014cbe0767",
          sort: 0,
          children: null,
          resourceName: "修改客户信息",
          resourceType: "PROCESS_DEFINITION_INFO",
          resourcePermissions: [
            "UPDATE_PROCESS_DEFINITION",
            "BIND_PROCESS_TRIGGER",
            "GRANT_ACTION",
          ],
        },
      ],
      departmentId: "b213fddf-2ed4-4025-9f39-7c1fd73a7c8f",
      id: "ceab9126-3744-4377-8f08-2a0c575265d3",
      parentId: { present: true },
      resourceName: "流程定义",
      resourcePermissions: [],
      resourceType: "PROCESS_DEFINITION",
      sort: 0,
    },
    {
      children: null,
      departmentId: "b213fddf-2ed4-4025-9f39-7c1fd73a7c8f",
      id: "5ba655dd-3fb1-42b8-ac2d-f1a1e33bb331",
      parentId: { present: true },
      resourceName: "审批组管理",
      resourcePermissions: [
        "CREATE_APPROVAL_GROUP",
        "UPDATE_TASK_NODE",
        "GRANT_ACTION",
      ],
      resourceType: "APPROVAL_GROUP",
      sort: 0,
    },
    // ...未复制完全
  ],
  choosedThisResource: true,
  departmentId: "b213fddf-2ed4-4025-9f39-7c1fd73a7c8f",
  id: "8f3cad8a-f834-4e6d-8680-2fc6427da202",
  parentId: { present: false },
  resourceName: "-",
  resourcePermissions: [
    "CREATE_SCRIPT_USER",
    "UPDATE_USER",
    "CREATE_ROLE",
    "LOCK_USER",
    "DELETE_ROLE",
    "UNEXPIRE_USER",
    "UNLOCK_USER",
    "UPDATE_ROLE",
    "CHANGE_PASSWORD",
    "UPDATE_DEPARTMENT",
    "CREATE_NAMESPACE",
    "READ_USER",
    "CREATE_USER",
    "CREATE_DEPARTMENT",
    "GRANT_ACTION",
    "EXPIRE_USER",
    "DELETE_USER",
  ],
  resourceType: "ROOT",
  sort: 0,
};

const finalSubDataAuth = [
  { firstName: "授权", level: 1 },
  { firstName: "创建脚本用户", level: 1 },
  { firstName: "创建资源组", level: 1 },
  { firstName: "创建部门", level: 1 },
  { firstName: "更新部门", level: 1 },
  { firstName: "创建角色", level: 1 },
  { firstName: "更新角色", level: 1 },
  { firstName: "删除角色", level: 1 },
  { firstName: "创建用户", level: 1 },
  { firstName: "更新用户", level: 1 },
  { firstName: "读取用户", level: 1 },
  { firstName: "删除用户", level: 1 },
  { firstName: "锁定用户", level: 1 },
  { firstName: "解锁用户", level: 1 },
  { firstName: "使用户过期", level: 1 },
  { firstName: "取消用户过期状态", level: 1 },
  { firstName: "重置用户密码", level: 1 },
  { firstName: "保证金", secondName: "更新保证金", level: 2 },
  { firstName: "客户信息", secondName: "读取客户", level: 2 },
  { firstName: "客户信息", secondName: "创建客户", level: 2 },
  { firstName: "客户信息", secondName: "更新客户", level: 2 },
  { firstName: "客户信息", secondName: "删除客户", level: 2 },
  {
    firstName: "流程定义",
    secondName: "财务出入金",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "财务出入金",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "财务出入金",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "触发器管理",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "触发器管理",
    thirdName: "创建触发器",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易录入",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易录入",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易录入",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易要素修改",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易要素修改",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "交易要素修改",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  { firstName: "流程定义", secondName: "开户", thirdName: "授权", level: 3 },
  {
    firstName: "流程定义",
    secondName: "开户",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "开户",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "授信额度变更",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "授信额度变更",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "授信额度变更",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "修改客户信息",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "修改客户信息",
    thirdName: "流程定义修改",
    level: 3,
  },
  {
    firstName: "流程定义",
    secondName: "修改客户信息",
    thirdName: "流程绑定触发器",
    level: 3,
  },
  { firstName: "审批组管理", secondName: "授权", level: 2 },
  { firstName: "审批组管理", secondName: "创建审批组", level: 2 },
  { firstName: "审批组管理", secondName: "审批组关联任务节点", level: 2 },
  { firstName: "TEST20210409", secondName: "授权", level: 2 },
  { firstName: "TEST20210409", secondName: "创建资源组", level: 2 },
  { firstName: "TEST20210409", secondName: "更新资源组", level: 2 },
  { firstName: "TEST20210409", secondName: "删除资源组", level: 2 },
  { firstName: "TEST20210409", secondName: "创建部门", level: 2 },
  { firstName: "TEST20210409", secondName: "更新部门", level: 2 },
  { firstName: "TEST20210409", secondName: "删除部门", level: 2 },
  { firstName: "TEST20210409", secondName: "读取用户", level: 2 },
  { firstName: "TEST20210409", secondName: "创建交易簿", level: 2 },
  { firstName: "TEST20210409", secondName: "创建投资组合", level: 2 },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "授权",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "更新交易簿",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "读取交易簿",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "删除交易簿",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "创建交易",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "更新交易",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "读取交易",
    level: 3,
  },
  {
    firstName: "TEST20210409",
    secondName: "TEST20210409",
    thirdName: "删除交易",
    level: 3,
  },
];
